using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text.RegularExpressions;
using UnityEditor;
using UnityEngine;

// Headless verification that the props generated by Tools/AssetPipeline actually survive Unity's
// FBX import. The pipeline validates its own output in Blender, but nothing before this confirmed
// the Unity half: that every FBX is indexed by the AssetDatabase, yields a mesh with the same
// triangle count Blender exported, carries materials with the embedded palette texture attached,
// and has a .meta file.
//
// Two front doors, one implementation: ValidateFromCommandLine for
//   Unity -batchmode -projectPath . -executeMethod ArtAssetImportValidator.ValidateFromCommandLine
// and ArtAssetImportTests (EditMode) so CI and the Test Runner window cover the same ground.
//
// Success marker (grep for this in the Editor log): ART_IMPORT_OK
public static class ArtAssetImportValidator
{
    public const string SuccessMarker = "ART_IMPORT_OK";
    public const string FailureMarker = "ART_IMPORT_FAILED";

    private const string ModelsRoot = "Assets/_Project/Art/Models";
    private const string PaletteTexturePath = "Assets/_Project/Art/Textures/PlunderspellPalette.png";

    private static string ProjectRoot => Directory.GetParent(Application.dataPath).FullName;
    private static string ManifestPath =>
        Path.Combine(ProjectRoot, "Tools", "AssetPipeline", "asset_manifest.json");
    private static string ReportPath =>
        Path.Combine(ProjectRoot, "Logs", "art-import-report.txt");

    public sealed class Report
    {
        public readonly List<string> Failures = new List<string>();
        public readonly List<string> Lines = new List<string>();
        public bool Passed => Failures.Count == 0;
    }

    /// <summary>Entry point for -executeMethod. Writes Logs/art-import-report.txt and sets the
    /// process exit code, so a CI step can gate on it without parsing the Editor log.</summary>
    public static void ValidateFromCommandLine()
    {
        AssetDatabase.Refresh(ImportAssetOptions.ForceUpdate);
        var report = Validate();

        var text = string.Join("\n", report.Lines);
        Directory.CreateDirectory(Path.GetDirectoryName(ReportPath));
        File.WriteAllText(ReportPath, text + "\n");

        if (report.Passed)
        {
            Debug.Log($"{SuccessMarker}\n{text}");
        }
        else
        {
            Debug.LogError($"{FailureMarker}\n{text}");
        }

        EditorApplication.Exit(report.Passed ? 0 : 1);
    }

    public static Report Validate()
    {
        var report = new Report();
        var expectedTriangles = ReadExpectedTriangleCounts(report);

        var fbxOnDisk = Directory
            .GetFiles(Path.Combine(ProjectRoot, ModelsRoot), "*.fbx", SearchOption.AllDirectories)
            .Select(ToAssetPath)
            .OrderBy(path => path)
            .ToArray();

        if (fbxOnDisk.Length == 0)
        {
            Fail(report, $"no .fbx files found under {ModelsRoot}");
            return report;
        }

        var indexed = new HashSet<string>(AssetDatabase
            .FindAssets("t:Model", new[] { ModelsRoot })
            .Select(AssetDatabase.GUIDToAssetPath));

        foreach (var assetPath in fbxOnDisk)
        {
            ValidateModel(assetPath, indexed, expectedTriangles, report);
        }

        var palette = AssetDatabase.LoadAssetAtPath<Texture2D>(PaletteTexturePath);
        if (palette == null)
        {
            Fail(report, $"palette texture did not import: {PaletteTexturePath}");
        }
        else
        {
            report.Lines.Add($"[ok]   palette texture {palette.width}x{palette.height}");
        }

        report.Lines.Add(new string('-', 62));
        report.Lines.Add(report.Passed
            ? $"{SuccessMarker} — {fbxOnDisk.Length} model(s) imported cleanly."
            : $"{FailureMarker} — {report.Failures.Count} problem(s) across {fbxOnDisk.Length} model(s).");
        return report;
    }

    private static void ValidateModel(string assetPath, HashSet<string> indexed,
        IReadOnlyDictionary<string, int> expectedTriangles, Report report)
    {
        var key = Path.GetFileNameWithoutExtension(assetPath);

        if (!indexed.Contains(assetPath))
        {
            Fail(report, $"{key}: on disk but not indexed by the AssetDatabase (import failed)");
            return;
        }

        if (!File.Exists(Path.Combine(ProjectRoot, assetPath + ".meta")))
        {
            Fail(report, $"{key}: no .meta file was generated");
        }

        var contents = AssetDatabase.LoadAllAssetsAtPath(assetPath);
        var meshes = contents.OfType<Mesh>().ToArray();
        var materials = contents.OfType<Material>().ToArray();

        if (meshes.Length == 0)
        {
            Fail(report, $"{key}: imported without any mesh");
            return;
        }

        var triangles = meshes.Sum(mesh => mesh.triangles.Length / 3);
        var vertices = meshes.Sum(mesh => mesh.vertexCount);
        if (vertices == 0 || triangles == 0)
        {
            Fail(report, $"{key}: mesh is empty ({vertices} verts, {triangles} tris)");
            return;
        }

        if (expectedTriangles.TryGetValue(key, out var expected) && expected != triangles)
        {
            Fail(report, $"{key}: {triangles} triangles imported but the pipeline manifest " +
                         $"recorded {expected} — Unity and Blender disagree about the geometry");
        }

        if (materials.Length == 0)
        {
            Fail(report, $"{key}: imported without any material");
        }
        else if (materials.Any(material => material == null))
        {
            Fail(report, $"{key}: has a missing (null) material reference");
        }

        // Textures are embedded in the FBX, so Unity should extract at least one as a sub-asset.
        // A material whose mainTexture is null would render untextured grey in game.
        var untextured = materials
            .Where(material => material != null && material.HasProperty("_MainTex") && material.mainTexture == null)
            .Select(material => material.name)
            .ToArray();
        if (untextured.Length > 0)
        {
            Fail(report, $"{key}: material(s) with no texture bound: {string.Join(", ", untextured)}");
        }

        if (!HasFailureFor(report, key))
        {
            report.Lines.Add(
                $"[ok]   {key,-18} {triangles,5} tris  {vertices,5} verts  {materials.Length} material(s)");
        }
    }

    /// <summary>Triangle counts the Blender pipeline recorded for each prop. Parsed rather than
    /// deserialised: the manifest is generated by our own script with a flat, known shape, and
    /// pulling in a JSON package for four integers per asset is not worth the dependency.</summary>
    private static Dictionary<string, int> ReadExpectedTriangleCounts(Report report)
    {
        var counts = new Dictionary<string, int>();
        if (!File.Exists(ManifestPath))
        {
            report.Lines.Add($"[warn] no manifest at {ManifestPath}; skipping triangle cross-check");
            return counts;
        }

        var json = File.ReadAllText(ManifestPath);
        var entries = Regex.Matches(json, "\"(?<key>[A-Za-z0-9_]+)\"\\s*:\\s*\\{(?<body>[^{}]*)\\}");
        foreach (Match entry in entries)
        {
            var tris = Regex.Match(entry.Groups["body"].Value, "\"tris\"\\s*:\\s*(?<tris>\\d+)");
            if (tris.Success)
            {
                counts[entry.Groups["key"].Value] = int.Parse(tris.Groups["tris"].Value);
            }
        }
        return counts;
    }

    private static string ToAssetPath(string absolutePath)
    {
        var relative = absolutePath.Substring(ProjectRoot.Length).TrimStart(Path.DirectorySeparatorChar, '/');
        return relative.Replace('\\', '/');
    }

    private static void Fail(Report report, string message)
    {
        report.Failures.Add(message);
        report.Lines.Add($"[FAIL] {message}");
    }

    private static bool HasFailureFor(Report report, string key) =>
        report.Failures.Any(failure => failure.StartsWith(key + ":"));
}
