"""
Content fingerprints for the generated assets, so a rebuild only rewrites
what actually changed.

Why this exists: neither output format is byte-reproducible on its own.
Blender's FBX exporter always stamps the export time into the header, and
Cycles' sampling varies run to run, so re-running the pipeline rewrote all
13 FBX files and all 14 PNGs every single time — a few megabytes of
meaningless diff on a repo that deliberately commits its build artifacts.

Fingerprinting the *mesh* instead sidesteps the formats entirely: if the
geometry, UVs and materials a prop would export to are identical to what
the committed file was built from, the file is left alone.

(The other half of the determinism story is PYTHONHASHSEED — see the
README. Without it Blender's exporter derives FBX object UIDs from
salted string hashes, so the same mesh exports different bytes each run.)
"""
import hashlib
import json
import os

MANIFEST_PATH = os.path.join(os.path.dirname(os.path.abspath(__file__)), "asset_manifest.json")


def fingerprint_mesh(obj) -> str:
    """Hash of the mesh as a *shape*, independent of storage order.

    Each face contributes its corner positions and UVs in winding order,
    rotated to start at its smallest corner, plus the pigment it is painted
    with; the face records are then sorted. So this is sensitive to
    geometry, winding, UVs and materials — a flipped normal or a moved
    vertex changes it — but not to the order Blender happens to store
    faces in.

    That last part is the point: bmesh emits the faces of a prop built from
    spheres or a lathe in a different order from run to run (verified as a
    pure permutation — identical faces, windings and normals), which would
    otherwise make every prop look "changed" on every rebuild.
    """
    mesh = obj.data
    uv_layer = mesh.uv_layers.active
    pigments = [
        # material names are "<AssetKey>_<pigment>"; the pigment is the part
        # that actually describes the surface
        (m.name.split("_", 1)[1] if m and "_" in m.name else str(m))
        for m in mesh.materials
    ]

    records = []
    for poly in mesh.polygons:
        corners = []
        for loop_index in poly.loop_indices:
            vert = mesh.vertices[mesh.loops[loop_index].vertex_index]
            position = tuple(round(c, 5) for c in vert.co)
            uv = tuple(round(c, 5) for c in uv_layer.data[loop_index].uv) if uv_layer else ()
            corners.append((position, uv))
        start = min(range(len(corners)), key=corners.__getitem__)
        corners = corners[start:] + corners[:start]
        pigment = pigments[poly.material_index] if poly.material_index < len(pigments) else "?"
        records.append((pigment, tuple(corners)))

    h = hashlib.sha256()
    for record in sorted(records):
        h.update(repr(record).encode())
    return h.hexdigest()[:16]


def load() -> dict:
    if not os.path.isfile(MANIFEST_PATH):
        return {}
    with open(MANIFEST_PATH) as fh:
        return json.load(fh).get("assets", {})


def save(assets: dict) -> None:
    payload = {
        "_comment": "Generated by Tools/AssetPipeline/build_assets.py — do not hand-edit.",
        "assets": {k: assets[k] for k in sorted(assets)},
    }
    with open(MANIFEST_PATH, "w") as fh:
        json.dump(payload, fh, indent=2, sort_keys=True)
        fh.write("\n")
